{{ if .Values.persistence.createPVC  }}
{{ range $pvc := .Values.persistence.createPVC }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $pvc.name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ $pvc.storageClassName }}
  accessModes:
    - {{ $pvc.accessMode }}
  resources:
    requests:
      storage: {{ $pvc.size }}
---
{{- end }}
{{- end }}