name: helix-helmchart-ci
run-name: HELIX Helm Chart CI triggered by @${{ github.actor }}

on:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  aphp-chart-ci-workflow:
    uses: "aphp/ci-workflows/.github/workflows/chart-ci.yml@main"
    with:
      kubernetes-version: "1.24.2"
      chart-dir: "charts/helix"
      chart-values: "./charts/helix/ci/ct-values.yaml"